realms = Realm.create([
  { name: 'Azuregos' },
  { name: 'Borean Tundra' },
  { name: 'Eversong' },
  { name: 'Fordragon' },
  { name: 'Galakrond' },
  { name: 'Goldrinn' },
  { name: 'Gordunni' },
  { name: 'Grom' },
  { name: 'Lich King' },
  { name: 'Booty Bay' },
  { name: 'Deephome' },
  { name: 'Razuvious' },
  { name: 'Howling Fjord' },
  { name: 'Soulflayer' },
  { name: 'Greymane' },
  { name: 'Deathguard' },
  { name: 'Thermaplugg' },
  { name: 'Deathweaver' },
  { name: 'Blackscar' },
  { name: 'Ashenvale' }
])
